
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
   branches: [ master ]
    
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: [windows-2019]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore NuGet packages
      run: nuget restore Structurizr.sln
    
    - name: Build the Solution
      run: msbuild Structurizr.sln /p:Configuration=Release  /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
    - name: dotnet publish
      run: dotnet publish -c Release -o build

    - name: Zip files
      run: tar -a -c -f published_webapp.zip build
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
          name: published_webapp.zip
          path: ./published_webapp.zip
  
  Deploy: 
    runs-on: self-hosted
    needs: build

    steps:
    
    - name: Downdload artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: published_webapp.zip
        path: C:\actions-runner\_work\published_webapp\
      
    - name: Extract Tar archive
      run: Expand-Archive -LiteralPath C:\actions-runner\_work\published_webapp\published_webapp.zip -DestinationPath C:\actions-runner\_work\published_webapp\     
    - name: Deploy to IIS
      run: |
          iisreset /stop
          Remove-Item C:\actions-runner\_work\published_webapp\published_webapp.zip
          Copy-Item C:\actions-runner\_work\published_webapp\_build\* D:\deployment -Recurse -Force
          iisreset /start

